import Head from 'next/head'
import React from 'react';

const about = () => {
  return (
    <div>
      <Head>
        <title>About</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-8520107381438109"
     crossorigin="anonymous"></script>
      </Head>
      <div className="aboutContainer">
        <h1>About</h1>
        <div className="info">
          <p>Hello, my name is Yassin Laghzaouna and i&apos;m a front-end web developer from Morocco.</p>
          <p>I love designing and developing websites, and learning new technologies every day.</p>
        </div>
      </div>
    </div>
  )
}

export default about