import Head from 'next/head'
import Image from 'next/image'
import Main from '../Components/Main'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Orange - Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Main/>
    </div>
  )
}
