import Head from 'next/head'
import Image from 'next/image'
import About from '../Components/about'
import Contact from '../Components/contact'
import Main from '../Components/Main'
import Projects from '../Components/Projects'
import Skills from '../Components/skills'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Main/>
      <Projects/>
      <Skills/>
      <About/>
      <Contact/>
    </div>
  )
}
