import Head from 'next/head'
import React from 'react';
import Navbar from "../Components/Navbar.jsx"

const projects = () => {
  return (
    <div>
      <Head>
        <title>Orange - Projects</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    </div>
  )
}

export default projects