import Head from 'next/head';
import Image from 'next/image';
import React from 'react';
import { skills } from '../data';

const services = () => {
  return (
    <div>
      <Head>
        <title>Skills</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-8520107381438109"
     crossorigin="anonymous"></script>
      </Head>
      <div className="skillsContainer">
        <h1>Skills</h1>

        <div className="skills">
          {skills.map(skill =>(
            <div className="skillContainer" key={skill.id}>
              <div className="tooltiptext">{skill.name}</div>
              <Image src={`/pictures/technologies/${skill.image}`} alt={skill.name} width="60%" height="60%"/>
            </div>
          ))}
        </div>


      </div>
    </div>
  )
}

export default services